spring:
  datasource:
    url: jdbc:mysql://183.62.25.243:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.unluckyworker.appointment.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  # file:
    # name: D:\tomcat\apache-tomcat-9.0.34\webapps\appointment\WEB-INF\classes\appointment.log
  pattern:
    file: "%-5level  %msg%n"
    console: "%-5level  %msg%n"